version: '2'

services:
  mysql:
    image: mariadb
    container_name: "passwords-mysql"
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: ./docker/php/
    container_name: "passwords-php"
    restart: on-failure
    links:
      - mysql
    volumes:
      - /var/www/html
      - ./src/:/var/www/html/custom_apps/passwords
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql:3306

  web:
    build: ./docker/nginx/
    container_name: "passwords-nginx"
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes_from:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "passwords-phpmyadmin"
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "nextcloud"
      PMA_ABSOLUTE_URI: http://localhost:8080
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: nextcloud

  mail:
    image: mailhog/mailhog
    container_name: "passwords-mail"
    user: root
    ports:
      - 1080:1080
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:1080
      MH_UI_BIND_ADDR: 0.0.0.0:1080

  iconserver:
    image: matthiasluedtke/iconserver
    container_name: "passwords-iconserver"
    environment:
      PORT: 7070

volumes:
  mysql: